<a href="https://colab.research.google.com/github/as-bestinclass/SDR_DataAnalysis/blob/main/outreach_performance_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analysis of Outreach Performance Data


In this notebook, we'll load and analyze a dataset related to the activity tracking of different users in a customer outreach or sales program.
The aim is to identify top performers based on various metrics and propose them for promotion to coaching roles.


## Load the Data
Let's start by loading the data and looking at the first few rows.

In [2]:
import pandas as pd

# Load the data
data = pd.read_csv('/content/export-reports-table-1690812623149.csv')

# Display the first few rows of the data
data.head()

,User ID,User name,User locked,Cumulative booked meetings,Prospects added,Prospects active,Prospects contacted,Meeting conversion rate,Touches per prospect,Emails delivered,Outbound calls,LinkedIn tasks completed,Other tasks completed,Overdue tasks,Response time,Responses count
0,1,#Outreach Admin,False,0,0,0,2,0.00,1,0,2,0,0,0,0.0,0
1,12,Edward Amaral,False,1,0,0,2,1.00,1,0,0,0,0,0,0.0,0
2,22,Paola Salamanca,True,0,2,2,0,0.00,0,0,0,0,0,2,0.0,0
3,26,Dan McGovern,True,1,0,0,1,1.00,1,0,0,0,0,4,0.0,0
4,28,Beth Murdent,False,1,40,20,76,0.03,3,130,92,65,8,0,0.0,0


The data includes information about the user (ID, name, and lock status), activity metrics (calls, emails, LinkedIn tasks, other tasks), and performance metrics (prospects added/contacted/active, booked meetings, meeting conversion rate, response time).


## Define Performance Metrics
To identify the top performers, we'll use the following metrics:

1. Who has made the most calls and emails for prospecting: We'll use the 'Outbound calls' and 'Emails delivered' columns.
2. Who has had the most success booking meetings: We'll use the 'Cumulative booked meetings' column.
3. Who has worked diligently without giving up: We'll use the sum of 'LinkedIn tasks completed' and 'Other tasks completed'.

For each of these metrics, we'll rank the users and give them scores. Then we'll add up these scores to get a final score for each user. The top 10 users with the highest final scores will be considered the top performers.

In [3]:

# Create new columns for the sum of calls and emails, and the sum of LinkedIn and other tasks completed
data['Calls and Emails'] = data['Outbound calls'] + data['Emails delivered']
data['Tasks Completed'] = data['LinkedIn tasks completed'] + data['Other tasks completed']

# Rank users by each of the three metrics and sum the ranks to get a final score
data['Calls and Emails Rank'] = data['Calls and Emails'].rank(ascending=False)
data['Booked Meetings Rank'] = data['Cumulative booked meetings'].rank(ascending=False)
data['Tasks Completed Rank'] = data['Tasks Completed'].rank(ascending=False)

data['Final Score'] = data['Calls and Emails Rank'] + data['Booked Meetings Rank'] + data['Tasks Completed Rank']

# Get the top 10 users by final score
top_performers = data.nsmallest(10, 'Final Score')

# Return the top 10 performers' user names and final scores
top_performers[['User name', 'Final Score']]

                User name  Final Score
1332           Renee Jett         10.0
2464     Shelby Greenwell        146.0
2162      Tyler Tonkovich        153.0
1826        Gianna Rosado        169.5
1990     Michael Williams        175.0
2521   Christopher Carter        192.0
1321  Christie Vanderhoof        223.5
2177        Shayna Conrad        248.5
1358    Catherine Vazquez        270.5
1670      Alberto Acevedo        272.0


The top 10 performers based on the defined metrics are displayed above. These individuals have consistently made a large number of outbound calls and emails, successfully booked meetings, and completed their tasks, making them excellent candidates for promotion to coaching roles.


## Detailed Performance Metrics for Top Performers
Let's look at the detailed performance metrics for these top performers.

In [4]:

# Extract the required columns for the top performers
top_performers_metrics = top_performers[['User name', 'Outbound calls', 'Emails delivered',
                                         'Cumulative booked meetings', 'Other tasks completed']]

top_performers_metrics.reset_index(drop=True, inplace=True)
top_performers_metrics

,User name,Outbound calls,Emails delivered,Cumulative booked meetings,Other tasks completed
0,Renee Jett,1459,4294,78,686
1,Shelby Greenwell,849,4110,52,237
2,Tyler Tonkovich,2713,4304,41,248
3,Gianna Rosado,583,4908,25,0
4,Michael Williams,1319,284,38,537
5,Christopher Carter,631,1274,38,325
6,Christie Vanderhoof,1813,1357,22,393
7,Shayna Conrad,1210,581,29,338
8,Catherine Vazquez,819,3345,17,30
9,Alberto Acevedo,693,853,50,260


The detailed performance metrics for the top 10 performers are displayed above. These individuals have been highly active in their roles, as indicated by the number of outbound calls and emails they've made, the number of meetings they've booked, and the other tasks they've completed.